version: "3"
services: 
  jenkins-master:
    image: apemon/jenkins-master:latest
    environment:
      - JAVA_OPTS="-Xmx2048m"
    ports:
      - "10080:8080"
      - "50000:50000"
    volumes:
      - ./home:/var/jenkins_home
      - ./logs:/var/log/jenkins
      - /var/run/docker.sock:/var/run/docker.sock

